name: Update NSFW Hosts List

on:
  schedule:
    - cron:  '0 0 * * *'   # every day at 00:00 UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download NSFW adblock list
        run: |
          curl -sSL \
            https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/nsfw.txt \
            -o adblock-nsfw.txt

      - name: Convert to hosts format with stats
        run: |
          # Extract raw domains count
          DOMAIN_COUNT=$(grep -c '^||' adblock-nsfw.txt)

          # Build output file
          {
            echo "# NSFW AdAway hosts list"
            echo "# Updated: $(date -u +'%Y-%m-%d %H:%M:%SZ')"
            echo "# Domains blocked: ${DOMAIN_COUNT}"
            echo ""

            # Convert each ||domain^ into two hosts entries
            grep '^||' adblock-nsfw.txt \
              | sed -E 's/^\|\|([^^]+)\^$/0.0.0.0 \1\n0.0.0.0 www.\1/'
          } > nsfw-hosts.txt

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add nsfw-hosts.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update NSFW hosts (${{ steps.build.outputs.DATE }})"
            git push
          fi
